//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMX4TextTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMX4TextTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40=0
        ///41=1
        ///42=2
        ///43=3
        ///44=4
        ///45=5
        ///46=6
        ///47=7
        ///48=8
        ///49=9
        ///4A=A
        ///4B=B
        ///4C=C
        ///4D=D
        ///4E=E
        ///4F=F
        ///50=G
        ///51=H
        ///52=I
        ///53=J
        ///54=K
        ///55=L
        ///56=M
        ///57=N
        ///58=O
        ///59=P
        ///5A=Q
        ///5B=R
        ///5C=S
        ///5D=T
        ///5E=U
        ///5F=V
        ///60=W
        ///61=X
        ///62=Y
        ///63=Z
        ///64=a
        ///65=b
        ///66=c
        ///67=d
        ///68=e
        ///69=f
        ///6A=g
        ///6B=h
        ///6C=i
        ///6D=j
        ///6E=k
        ///6F=l
        ///70=m
        ///71=n
        ///72=o
        ///73=p
        ///74=q
        ///75=r
        ///76=s
        ///77=t
        ///78=u
        ///79=v
        ///7A=w
        ///7B=x
        ///7C=y
        ///7D=z
        ///7E=/
        ///83=+
        ///84=-
        ///85=,
        ///86=.
        ///87=!
        ///88=?
        ///89=&quot;
        ///8A=”
        ///8B=’.
        /// </summary>
        internal static string CharacterTable {
            get {
                return ResourceManager.GetString("CharacterTable", resourceCulture);
            }
        }
    }
}
